# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerNumber', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('customerName', models.CharField(max_length=64)),
                ('contactLastName', models.CharField(max_length=64)),
                ('contactFirstName', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=15)),
                ('addressOne', models.CharField(max_length=128)),
                ('addressTwo', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=64)),
                ('postalCode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=64)),
                ('creditLimit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeNumber', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('lastName', models.CharField(max_length=128)),
                ('firstName', models.CharField(max_length=128)),
                ('extension', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('jobTitle', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeCode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('addressOne', models.CharField(max_length=128)),
                ('addressTwo', models.CharField(blank=True, max_length=128, null=True)),
                ('city', models.CharField(max_length=64)),
                ('postalCode', models.CharField(max_length=8)),
                ('country', models.CharField(max_length=64)),
                ('territory', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNumber', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('orderDate', models.DateField()),
                ('requiredDate', models.DateField()),
                ('shippedDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=32)),
                ('comments', models.CharField(max_length=256)),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOrdered', models.IntegerField()),
                ('priceEach', models.IntegerField()),
                ('orderLineNumber', models.IntegerField()),
                ('orderNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('checkNumber', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('paymentDate', models.DateField()),
                ('amount', models.FloatField()),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productCode', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('productName', models.CharField(max_length=128)),
                ('productScale', models.CharField(max_length=128)),
                ('productDescription', models.CharField(max_length=128)),
                ('quantityInStock', models.IntegerField()),
                ('buyPrice', models.IntegerField()),
                ('MSRP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('productLine', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('textDescription', models.TextField()),
                ('htmlDescription', models.TextField()),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.Customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productLine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.ProductLine'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='productCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.Product'),
        ),
        migrations.AddField(
            model_name='employee',
            name='officeCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.Office'),
        ),
        migrations.AddField(
            model_name='employee',
            name='reportsTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkr_user.Employee'),
        ),
    ]
