# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkr_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='signUpDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
