# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkr_user', '0002_customer_signupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customerName',
        ),
        migrations.AddField(
            model_name='customer',
            name='customerFirstName',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='customerLastName',
            field=models.CharField(default=b'', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='creditLimit',
            field=models.IntegerField(default=100),
        ),
    ]
