# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkr_user', '0003_auto_20171204_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MSRP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='htmlDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='productline',
            name='textDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
