# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkr_user', '0005_auto_20171204_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
