# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkr_user', '0008_auto_20171205_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customerNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer', to='pkr_user.Customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customerNumber',
            field=models.ForeignKey(default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='pkr_user.Customer'),
        ),
    ]
