# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkr_user', '0010_auto_20171205_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantityInStock',
        ),
    ]
